### ISSUE TITLE
Reporting Download

### ISSUE THREAD

**Issue by lgarciab0717** [OfficeDev/microsoft-teams-apps-company-communicator#1058] opened 2023-06-02 14:39 UTC
I have a problem downloading the reports with the Senders accounts, we can only download them from the global administrator account that made the implementation, 

To take into account the implementation was made from a admin.tenant@domain.onmicrosoft.com domain and deployed in the tenant where users use the juan.perez@domain.com domain, for us the report is indispensable.

![Imagen de WhatsApp 2023-05-30 a las 10 34 30](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134085994/022898a5-0821-4015-a4ac-0db914266b88)

**Comment by gsv022** [comment] 2023-06-05 06:22
Hi @lgarciab0717,
Thanks for raising the query. This is already a known issue. The fix has been identified. Currently it is in the phase of testing and hopefully it will be available by the end of June.

Here is the workaround for the Export issue.

- Go to Azure Portal

- Click on the resource group that has been used for CC

- Go to Storage Account.

- Select Storage browser

- Go to Blob Containers

- Click on export data blobs.

- Copy the desired zip folder name from teams and search for required zip folder in export data blobs.

- Click on the zip folder that needs to download

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Download the zip file.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Once the issue is resolved,  we will update you.

**Comment by PrithuMahisha** [comment] 2023-07-06 12:37
@gsv022 - Could you please provide an update on this since July has ended. 
Please provide an ETA for when will it be resolved.

**Comment by gsv022** [comment] 2023-07-11 06:19
Hi @PrithuMahisha ,
Thanks for the patience. The issue has been fixed by the concerned team. Please check and confirm the export functionality working status from your end.

Keep us posted

**Comment by lgarciab0717** [comment] 2023-07-11 18:59
The problem has been satisfactorily resolved.

Thank you!

**Closed** 2023-07-12 03:21 UTC
Labels: Needs: author feedback

**Comment by reece-r** [comment] 2023-07-24 14:10
Hi @gsv022 , I am having the same issue but when I follow these steps to the storage account, there is no 'exportdatablobs' container. App Service, and all 3 Functions deployment status is Success (Active) and this is version 5.4.1
