### ISSUE TITLE
Permissions needed. Ask your IT admin to enable this option for you in company communicator

### ISSUE THREAD

**Issue by sudheesh145** [OfficeDev/microsoft-teams-apps-company-communicator#556] opened 2021-11-21 09:25 UTC
I am getting all the below error when trying the send message using the below option, I can only send to everyone none of the other options working, I have followed and assigned the permission in Authors app and still not working. Any leads would really help.

![image](https://user-images.githubusercontent.com/57366953/142756523-b2be1105-4e7e-4608-8925-5a079d5572eb.png)
![image](https://user-images.githubusercontent.com/57366953/142756538-9009d78a-efdd-42ce-8941-77005c270f38.png)
![image](https://user-images.githubusercontent.com/57366953/142756543-2399f7d6-54fc-4a36-9446-cb754abb043f.png)

**Comment by doriansmm97** [comment] 2021-11-22 14:27
i have the same problem

**Comment by Porkai-Pandian** [comment] 2021-11-22 19:57
Hi @sudheesh145

Thanks for raising the issue, please check if the user app in installed to the Teams channel, Team group names will appear in the dropdown only if the user app in installed.

**Comment by bchamnarnkit** [comment] 2021-11-23 04:46
I have the same issue for the last option. The person who tried to send out the message was the IT Global Admin, Is there a documentation on how to enable this option? - Sending to M365 Groups, Distribution Groups or Security Groups? Thanks!

**Comment by priyank29** [comment] 2021-11-24 02:29
@sudheesh145 @bchamnarnkit For the 4th option please check if the graph permissions are granted.

**Comment by Tobias-Ekperigin** [comment] 2021-11-29 13:48
We have the same issue. After upgrading to the new version. Now not able to send to anyone from the Authors Application 

![image](https://user-images.githubusercontent.com/65253262/143879008-5dee6936-64fd-43d1-88b6-a84c8cdccd3a.png)

None of the options above work. 

I can confirm that all required permissions have been applied and consented to the user application as mentioned in the guide. @priyank29 

![image](https://user-images.githubusercontent.com/65253262/143879415-50334d23-c935-4d66-ac76-91ff9931198c.png)

**Comment by doriansmm97** [comment] 2021-11-29 15:45
@Tobias-Ekperigin the new configuration is in the new graph app, not in the author app

**Comment by sudheesh145** [comment] 2021-11-29 16:21
> Hi @sudheesh145
> 
> Thanks for raising the issue, please check if the user app in installed to the Teams channel, Team group names will appear in the dropdown only if the user app in installed.

@Porkai-Pandian Yes it is installed in the teams only but still getting the error

**Comment by sudheesh145** [comment] 2021-11-29 16:22
> @Tobias-Ekperigin the new configuration is in the new graph app, not in the author app

I have the same issue and have all permission assigned to graph app

**Comment by Tobias-Ekperigin** [comment] 2021-11-29 18:13
@doriansmm97  Sorry I should have made myself clearer. The permissions are applied correctly. Still I have this issue. Like @sudheesh145

**Comment by bchamnarnkit** [comment] 2021-11-30 04:46
Hi @priyank29 , Thanks for your message, I have checked and the permissions and Graphs APIs have been granted accordingly,
<img width="747" alt="Graph permission grants v2" src="https://user-images.githubusercontent.com/84174370/143987152-4ea17d5a-a599-4af9-a44d-26f08bb0c967.png">
 I have attached screenshots for your reference 
<img width="506" alt="Sending to Groups Error" src="https://user-images.githubusercontent.com/84174370/143987147-14992e16-f752-4c71-a153-60c7b163560a.png">

**Comment by ecmansur** [comment] 2021-12-13 20:29
Guys, I solved this problem adding 2 permissions:
![image](https://user-images.githubusercontent.com/96084578/145883901-c256eaf1-bad7-4a3c-b225-211a1ef47e8e.png)

**Comment by bchamnarnkit** [comment] 2022-01-11 07:57
Thanks @ecmansur , just to confirm. This is added to the author version of the app correct? And once that is added did you need to sync or stop and restart any app services? Again, appreciate your help :)

**Comment by Tobias-Ekperigin** [comment] 2022-01-17 13:44
I tried adding these permissions. But sadly to no effect. Still the same error of "Permissions Needed ask your admin to enable this for you"

**Comment by almaucla** [comment] 2022-02-07 16:23
> Guys, I solved this problem adding 2 permissions: ![image](https://user-images.githubusercontent.com/96084578/145883901-c256eaf1-bad7-4a3c-b225-211a1ef47e8e.png)

Where did you apply these 2 permissions? Have you done any additional steps afterwards?

**Comment by Tobias-Ekperigin** [comment] 2022-02-07 16:25
What I did to fix this. Was to fully delete all traces of the application from the tenant. Then use the PowerShell Deployment instead and that worked.

**Comment by ayotwice** [comment] 2022-05-09 10:48
I have this same issue any help with it
![image](https://user-images.githubusercontent.com/16527776/167395186-86e663e4-b18c-4436-aea6-55860a6b304d.png)

**Comment by gsv022** [comment] 2022-05-10 07:58
Hi all,
In v5.x, the 4th option might be disabled due to [permissions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2FDeployment-guide&data=04%7C01%7Cv-saigattu%40microsoft.com%7Cd5d5c92e3fde463a9cae08da12cf47b3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637842978742205765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2p1IhE8JqoM6SR3zMkFwZSwVsxBDwXu1%2Bu9FOndj1JQ%3D&reserved=0) needed for the Graph App registration.
•	Could you please verify if the below permissions has been added and the admin consent is granted? 
•	Once the API permission is added, request you to wait for a few hours and re-try sending the message, and let us know if 
        the issue is resolved.

![image](https://user-images.githubusercontent.com/98143492/167577630-8ac8c1f5-c86e-4b40-b210-1a3cc3543737.png)

**Comment by ayotwice** [comment] 2022-05-10 12:17
> 

Yes all these permission have been set

**Comment by gsv022** [comment] 2022-05-11 13:47
Hi,
If permissions are already granted, could you please cross verify the secret that is created during graph app registration is same as  configured in azure app service?

**Comment by cristianoag** [comment] 2022-05-18 01:08
I reinforce what @gsv022 said. Look at your secret values. most likely they are wrong in keyvault and the application is not using the app registrations appropriately. @ayotwice

**Comment by ndocosta** [comment] 2022-05-29 21:18
I got this same error, and solved it by:

- Going to the Teams Admin Center
- Selecting the Company Communicator Author App
- Clicking on "Permissions" tab
- Clicking on button "Review Permissions and Consent"
- Accepting the required permissions.

In my case, app registrations were created on an azure subscription different from the Teams subscription.
- Azure solution and app registration in one tenant and Teams Apps in a different Tenant.

Hope this helps!

**Comment by gsv022** [comment] 2022-06-01 05:21
Hi,
​We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Closed by gsv022** 2022-06-01 05:21 UTC
