### ISSUE TITLE
Error sending message to one user only

### ISSUE THREAD

**Issue by WaldekBarros** [OfficeDev/microsoft-teams-apps-company-communicator#1038] opened 2023-05-12 00:57 UTC
Guys, good night!

I need help with an error that is only occurring with one user in the company.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/e427a2af-1351-4e41-bc38-0c4a01a411f1)

I did a message sending test for a team where I and this user are. But I'm getting the following error in the report (I'm a Global Admin, so I can export).

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/71197076-5f92-41cd-89db-63d2feed7a4d)

Can you help me please?

**Comment by gsv022** [comment] 2023-05-12 06:48
Hi @WaldekBarros ,
Thanks for raising the query. Add one more user to the team. And can you please retry to send the message and confirm if the issue is happening for newly added user as well? If its fails for same old user then it something to do with the user configuration.

**Comment by WaldekBarros** [comment] 2023-05-12 13:44
Hi @gsv022,

I added a new user and the message was delivered without problems. However, the user "Renata" presented the same error.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/ce98d49c-fd3a-4050-a643-874b3c933cc2)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/4ff3e3ff-725f-4324-95dd-46a72e8084c1)

**Comment by WaldekBarros** [comment] 2023-05-12 18:14
`User ID,UPN,Name,User Type,Delivery Status,Status Reason,Error
825eb63f-eeb8-4795-ab0a-0220ac1f76b4,raquel.xxxxxx@xxxxxx.com.br,Raquel Amaral,Member,Failed,403 : Failed,"Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94"`

**Comment by gsv022** [comment] 2023-05-15 06:08
Hi @WaldekBarros ,
It is possible that the user who is not receiving the messages may have deleted the cc-chat in their own tenant. Additionally, please confirm the user's current activity status within the organization.

**Comment by gsv022** [comment] 2023-05-23 04:18
@WaldekBarros , Please let us know if you have any queries otherwise we can make it to closure

**Comment by gsv022** [comment] 2023-05-25 03:59
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Closed by gsv022** 2023-05-25 03:59 UTC
Labels: Needs: author feedback

**Comment by WaldekBarros** [comment] 2023-06-30 13:59
@gsv022, just to give you feedback on the error.

The problem is occurring because the user at some point blocked the application according to the print. Is there a possibility to disable blocking?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/824aff2f-fb9b-4ed0-aeb5-3250bbc0b94b)
