### ISSUE TITLE
I can send out the message but only myself received the message successfully.

### ISSUE THREAD

**Issue by chan228228** [OfficeDev/microsoft-teams-apps-company-communicator#1316] opened 2024-01-23 03:25 UTC
Below is the error detail, any idea? Thank you..

Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 95

**Comment by gsv022** [comment] 2024-01-23 14:42
Hi @chan228228 ,
Thanks for raising the query. Could you please confirm on the below points.

-Please share the repo url and branch used for deployment. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a37cd049-fd0a-4914-ab06-cbc7d7e22879)

- How many member are present in the team? Share the success and failure count of the latest sent message.

**Comment by chan228228** [comment] 2024-01-24 01:21
Hi @gsv022 

Same as yours.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157443060/d5631d1a-5c48-409f-9f45-4f1240a2b7da)

I am the only success receiver.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157443060/26a8198c-0f75-4a65-a17d-b10d49a74736)

**Comment by chan228228** [comment] 2024-01-30 07:32
@gsv022 any update, please?

**Comment by gsv022** [comment] 2024-01-31 07:00
Hi @chan228228 ,
Within the shared screenshot above please click on logs and show the deployment status with a supporting screenshot.

**Comment by gsv022** [comment] 2024-02-09 11:50
Hi @chan228228 ,
Thanks for sharing the screenshot. It seems that dotnet runtime version for function apps are not updated to ~4. Could you please perform the 1st and 2nd steps as per the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version).

**Comment by chan228228** [comment] 2024-02-14 02:03
Hi @gsv022  The error prompts up when I tried to restart the Azure function apps.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157443060/f22b6024-c651-4cbf-a203-e010a5e76e59)

**Comment by gsv022** [comment] 2024-02-15 05:39
Hi @chan228228 ,

- Please verify the function run time version is set to ~4.  
Go to Prep-Function-->Click on configuration-->Check for function runtime version.

- If the above step is already done, perform SYNC for prep-function in deployment center once again.
- Check for other two functions -Data Function and Function as well. If the issue is same, please perform the above step to resolve the issue.

**Comment by chan228228** [comment] 2024-02-16 01:23
Hi @gsv022 

- Double checked prep-function app, data-function app, function app and both of function run time versions are set to ~4.
- Both of them SYNC successfully.
- No error in the Application Insights.
- Now the tap is empty and the "Save" button is greyed out, I cannot add the app from Teams app/web anymore.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157443060/7b364dd0-496b-4b56-80e8-d20892d165fe)

**Comment by gsv022** [comment] 2024-02-20 03:57
Hi @chan228228 ,
We already shared the call summary via mail. Please let us know if you have any queries with standard version of CC otherwise we can make it to closure.

**Comment by chan228228** [comment] 2024-02-21 02:07
Hi @Sai Venkat Gattu (LTIMindtree ***@***.***>

The groups are not searchable in CC app.
***@***.***
Please advise if the permissions below are required in new CC app version 5.5, or something else config is required.
[image]<https://user-images.githubusercontent.com/96084578/145883901-c256eaf1-bad7-4a3c-b225-211a1ef47e8e.png>

Thanks.

Best Regards,

Caesar Chan
Senior Digital Workplace Engineer

T：+852 3500 4616
***@***.***
DCH Business Innovations Limited
DCH Building, 20 Kai Cheung Road,
Kowloon Bay, Hong Kong

**Comment by gsv022** [comment] 2024-02-21 07:05
Hi @chan228228 ,
Here is the summary for reference.
During the call it is observed that messages are not getting delivered to the members in the group except author. 

- As a part of troubleshooting, it is noticed that there are 26 resources residing under same resource group. In deployments section, there are two deployments observed with two different base resource names.

- In addition to that the deployments done are pointing to custom repository and on top of that standard version has been connected by performing the SYNC.

- We mentioned that there would be conflict in configuration, feature mismatch etc., and it would be little challenge to troubleshoot here.

We recommended  to proceed with the fresh deployment pointing to ⁠[official repository](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator). If any arises during and after the fresh deployment, we will be more than happy to assist you.


If you have any further queries and to avoid any communication gaps, we have 16950 ticket to discuss the issue internally. We are closing the issue here.

**Closed by gsv022** 2024-02-21 07:05 UTC
Labels: Needs: attention :wave:
