### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by jupam18** [OfficeDev/microsoft-teams-apps-company-communicator#353] opened 2021-03-22 20:28 UTC
When deploying the solution, I get an error on this line

Communicator/web Microsoft.Web/sites/sourcecontrols the status says Conflict

This is the detail:

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

Am I doing something wrong?

Thanks.

**Comment by ATshirai** [comment] 2021-03-23 13:44
I don't think that was your fault.
I've gotten some deployment errors  caused by conflict.
You can sync the failed web application, I did it.
a) sign in Azure portal
b) select App Service
c) click the failed web application
d) select the Deployment center (classic) in left side
e) click sync

It's ok if you'll find "Deployment successfully" in the log.

Please see <https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure>

**Comment by jupam18** [comment] 2021-03-23 13:58
Thanks a lot, solved.
________________________________
De: ATshirai ***@***.***>
Enviado: martes, 23 de marzo de 2021 01:45 p. m.
Para: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
CC: jupam18 ***@***.***>; Author ***@***.***>
Asunto: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Deployment error (#353)


I don't think that was your fault.
I've gotten some deployment errors caused by conflict.
You can sync the failed web application, I did it.
a) sign in Azure portal
b) select App Service
c) click the failed web application
d) select the Deployment center (classic) in left side
e) click sync

It's ok if you'll find "Deployment successfully" in the log.

Please see https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure

**Comment by priyank29** [comment] 2021-03-25 09:55
@jupam18 as per above comments the issue seems to be resolved, so closing the issue.

**Closed by priyank29** 2021-03-25 09:55 UTC

**Comment by Miclarsen1** [comment] 2021-06-14 08:54
Don't think this works anymore, can't find anything to click on named Deployment center.
