### ISSUE TITLE
Failed to export detailed results - This card action is not supported by CC

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1117] opened 2023-08-15 09:51 UTC
Hi,
When I click on "export detailed results" in a sent message, everything seems to be ok and notification was then sent to Teams (in web browser) individually to me.
When I click on the allow button to accept communicator to accept permission to upload the zip file to my OneDrive, I get the message below. **This card action is not supported by CC**

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/a9a81060-ccc6-4728-a178-171059a33d89)

The communicator is version 5.3

I have followed instructions in other issue threads. e.g. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1001 & https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1001 and I concluded that:

- I am not the global Administrator in Azure!
- **AuthorAppPassword** was good matching the same password for communicator app registration client secret (expiring in 1 year)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/03ce56a2-d830-4894-b2f1-19a1128c357f) as in the communicator vault
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/8d2be182-cd23-41ff-8bfc-b8979ea4916d)

The 2 function apps (xxfn-prep & xxfn-data) configurations **AuthorAppPassword** matches as well.

- It is not sustainable to manually download the zip file from Azure storage account by Administrator on behalf of the end-user with this issue for band aid fix.

Can you please help me?

Thanks.
David

**Comment by gsv022** [comment] 2023-08-16 07:45
Hi @David-Liong ,
Thanks for raising the query.  This **export issue** and **4th sending option**(Permission need. Ask IT admin to enable this option for you) is caused by the sync to latest version only. We request you to close any  one of the issues -#1117 or #1116  as they are duplicate to each other.

- Upon sync it will connect to the latest version of Company Communicator that is what happened in your case. We recommend you to disconnect the existing repository **main** and connect to particular version i.e., v4.x
<img width="800" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/573553c2-8d2e-4ad4-a0ae-2e628f9fa4df">

- Do this for all 3-function apps, app service. 
- Once the status is successful in the logs section of each resource, please open the CC application in browser to avoid any cache issue.

**Comment by David-Liong** [comment] 2023-08-17 07:55
Hi @gsv022 

I did not know that sync by default it will connect to the latest version of Company Communicator, unless you change the location as it was not mention in wiki.

So are you able to update the wiki of v3 to v4 upgrade doco at https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide#4-deploy-to-your-azure-subscription of step 11 in section 4 to update the UI screenshot that **BEFORE** clicking on the sync button ensure that the [repository is pointing](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v4.x) to https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v4.x


I will close this issue ticket 1117

However, before I close this ticket, if caching is the issue, can I instead delete the company chat bot in Teams, uninstall company for user app from Teams Admin and re-install the company for user app again?

Thanks.

**Comment by gsv022** [comment] 2023-08-17 12:44
Hi @David-Liong ,
The v5.x is having another app registration called graph app registration without that 4th sending option or export functionality won't work. If v4.x is the target, please go with above mentioned approach i.e., connecting to v4.x. And re-installing the app won't do the needful

**Comment by gsv022** [comment] 2023-08-21 12:47
Closing this issue as this is a duplicate to #1116. We will follow up in 1116 issue from now on.

**Closed by gsv022** 2023-08-21 12:47 UTC
Labels: duplicate

**Comment by David-Liong** [comment] 2023-08-23 01:50
Hi @gsv022 
The intent was to upgrade to v4.x as being the temporary target from v3.x. Then ultimately upgrade from v4.x to v5.x

OK I will go with above mentioned approach i.e., sync to v4.x main branch repository. I will close this ticket but keep the other ticket https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1116 open
