### ISSUE TITLE
proactiveAppInstallation not installing app

### ISSUE THREAD

**Issue by GhustintheWizard** [OfficeDev/microsoft-teams-apps-company-communicator#1029] opened 2023-05-02 19:49 UTC
If I manually install the app on a test user, they will receive the message.  Per the troubleshooting:

1. Grant Admin consent to the application for all the graph permissions mentioned [here](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Deployment-guide#4-add-permissions-to-your-app).

Done

2. "ProactivelyInstallUserApp" configuration is enabled (set to "true") for the web app and the prep-function.

Verified that it is set to True in both web app and prep-function

3. "UserAppExternalId" configuration matches with the User app Id (in the Teams App manifest) for the web app.

Verified that the UserAppExternalID matches the ID listed in the Manifest.json file for the User app.

4. [Upload](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams) the User app to your tenant's app catalog so that it is available for everyone in your tenant to install.

Done

**Comment by v-royavinash** [comment] 2023-05-03 05:44
@GhustintheWizard Could you please share your teams outlook Id?

**Comment by GhustintheWizard** [comment] 2023-05-03 21:23
@v-royavinash We talking a personal email to send over company info?

**Comment by v-royavinash** [comment] 2023-05-04 00:29
@GhustintheWizard,  The issue is occurring due to a known issue with the Graph API endpoint. Apps without webappinfo defined are failing to install in personal scope via teamwork/installed Apps in user delegate context. 

However, it should be noted that the problem does not lie with the company communicator. As it uses the same workflow to proactively install the app hence CC is also impacted. The Graph team is currently working on resolving this issue on a priority basis. We will keep you informed as soon as the issue is resolved

**Comment by GhustintheWizard** [comment] 2023-05-04 00:40
@v-royavinash  Thanks for the update!

**Comment by gsv022** [comment] 2023-05-30 13:14
Could you please confirm if the issue is resolved or not

**Comment by GhustintheWizard** [comment] 2023-05-30 18:11
It has not been resolved yet.  If I target a user that has NOT manually added the Comp Communicator app in Teams (and also has NOT had the app added via membership to a team that has the app added), then the message fails to send to that user.

If I manually add the Comp Communicator app at the target users device, then resend the message, the user will receive it.

So the proactiveAppInstallation feature is still not currently working.

**Comment by gsv022** [comment] 2023-06-12 13:38
@GhustintheWizard , We have sent you an email. Hope you received it.

**Comment by GhustintheWizard** [comment] 2023-06-15 14:13
I replied to your email with additional information regarding meeting times.

**Comment by gsv022** [comment] 2023-06-16 11:34
We haven't heard anything after this mail in the same thread. Could you please reply on top of this.

> @GhustintheWizard , We tried reaching out via given mail id. Awaiting your reply <img alt="image" width="505" src="https://user-images.githubusercontent.com/98143492/246053818-01b52510-d68e-492f-94a7-440239df38dc.png">

**Comment by GhustintheWizard** [comment] 2023-06-16 13:54
I replied to your original email again with times I am available.

**Comment by gsv022** [comment] 2023-07-04 11:09
Hi Justin,
Hope you have received the meeting invite. Please do accept if the scheduled time suits for you

**Comment by gsv022** [comment] 2023-07-10 07:34
@GhustintheWizard ,
Please let us know if you have any queries otherwise we can make it to closure.

**Comment by GhustintheWizard** [comment] 2023-07-12 15:23
> 

It was great to meeting regarding the issue.  I believe we are just waiting for an update on the expected behavior for a user that has previously removed the user app, but now the proactive process won't re-install it.

**Comment by gsv022** [comment] 2023-07-17 09:19
Hi @GhustintheWizard ,
Could you please confirm, is it happening with one particular user?

**Comment by GhustintheWizard** [comment] 2023-07-18 14:40
In my testing with your support team, we found that any user that had the app installed previously, but then removed the user app, was not having the app proactively reinstalled when a new message was sent to them.

**Closed** 2023-07-26 01:00 UTC
Labels: Needs: author feedback, Status: no recent activity
