### ISSUE TITLE
"Preview in this channel" not working

### ISSUE THREAD

**Issue by malikahoffer** [OfficeDev/microsoft-teams-apps-company-communicator#649] opened 2022-02-23 08:39 UTC
If I have a message draft in the Company communicator authors app and want to "preview in this channel" to see how the message will look like, the message is not posted in the general channel. I get this error message:
![image](https://user-images.githubusercontent.com/94395515/155285454-2ce94b6b-7426-4719-94f2-0cb1452ef189.png)

**Comment by v-royavinash** [comment] 2022-02-23 10:36
Hi @malikahoffer , There might be some configuration mismatch while deploying the app. Could you please share us the Application Insights logs. Also will recommend to do the deployment once again with following the steps mentioned in the deployment guide.

**Comment by gsv022** [comment] 2022-04-05 08:40
Hi @malikahoffer ,
For now we are closing this issue request considering the issue is resolved.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.

**Closed** 2022-04-05 08:41 UTC
Labels: details needed
