### ISSUE TITLE
App blocked for majority of users in Permission policy - Failing to send messages for all users

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-company-communicator#484] opened 2021-08-11 09:59 UTC
Hi Team,
App is allowed in permission policy for 800 users and app is blocked for 3200 users. All above 4000 users are members of M365 group. 

When trying to send message to M365 group, message is not even sending to 800 users. Whole process is failing and showing error message as app forbidden to install.

Tried with dev tenant which contains 25 licenses and it is working as expected.

**Comment by bungleweed** [comment] 2021-09-13 20:00
Do you want everyone to be able to receive the messages (all 4000)? If not don't select the send to everyone option. Instead create  or resuse a group to send to with the 800 users you want send to. IF you want to send to all 4000 they all need a permissions policy that allows them to install the end user app. IF not the proactive install will fail to these recipients. You can turn off the proactive install of the end user app but don't recommend this.

**Comment by priyank29** [comment] 2021-10-01 06:06
@SubbaReddi Can you try the latest commit? The issue is resolved #509. Closing this.

**Closed by priyank29** 2021-10-01 06:06 UTC
