### ISSUE TITLE
 Issues sending CC message to 300k users

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-company-communicator#578] opened 2021-12-14 17:45 UTC
****Customer is attempting to send a message to all user (300K+), CC has been trying to sync for the last 5 hours, has an urgent message that needs to go out asap**** 

![CC syncing issue Dec14](https://user-images.githubusercontent.com/64435811/146051680-15d4390c-12a1-45c1-a1b4-ac68aba529e0.png)

**Comment by Porkai-Pandian** [comment] 2021-12-15 19:37
Hi @scjohnmsft,

Thank you for raising the query here, there is already an email discussion going on about this issue, updating the comment for visibility here.

**Comment by Porkai-Pandian** [comment] 2021-12-17 19:15
Confirmed with customer that the issue is resolved, hence marking it as closed

**Closed by Porkai-Pandian** 2021-12-17 19:15 UTC
