### ISSUE TITLE
Users can reply to bot

### ISSUE THREAD

**Issue by M1mmboga** [OfficeDev/microsoft-teams-apps-company-communicator#642] opened 2022-02-16 12:00 UTC
Hello Team,
There is an issue where users are now replying to the bot, please return to notification only?

**Comment by Porkai-Pandian** [comment] 2022-02-17 00:49
Hi @M1mmboga 

Thank you for raising the query, can you please confirm if you see this reply to bot in individual user chats or Teams channel group chats, because we don't see reply option in individual user chats.

**Comment by Mikhail2k15** [comment] 2022-02-17 17:44
@Porkai-Pandian "see this reply to bot in individual user chats". It is a known issue in the Teams platform.  Sometimes notification only bots don't respect this option and show for an end-user the replay input

**Comment by gsv022** [comment] 2022-03-31 12:43
Hi @M1mmboga 
The issue mentioned is a known issue in the Teams platform and not specific to CC.
Once the issue is fixed for the Teams platform the same will be reflected to CC.
Hence we are closing the issue.

**Closed by gsv022** 2022-03-31 12:43 UTC
