### ISSUE TITLE
Author app not retrieving recipients when sending messages

### ISSUE THREAD

**Issue by jcsul** [OfficeDev/microsoft-teams-apps-company-communicator#360] opened 2021-03-30 07:59 UTC
Hi There,
we have just configured the company communicator as well as the author app and i am currently trying to send a test message, however when I send to a teams channel/team members no recipients are detected and no messages are sent. 

There are no error messages anywhere that I can see, other than the following message when trying to Export details:
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

Any help would be appreciated
thanks!

**Comment by faalive** [comment] 2021-03-30 13:18
I have same behaviour but checking log I read this: " 403 : The bot is not part of the conversation roster". To be honest I don't know where or how to correct this issue :(

**Comment by jcsul** [comment] 2021-03-30 13:23
> I have same behaviour but checking log I read this: " 403 : The bot is not part of the conversation roster". To be honest I don't know where or how to correct this issue :(

Where did you see this log out of interest? i can double check and see if i have the same issue

**Comment by faalive** [comment] 2021-03-30 13:33
> > I have same behaviour but checking log I read this: " 403 : The bot is not part of the conversation roster". To be honest I don't know where or how to correct this issue :(
> 
> Where did you see this log out of interest? i can double check and see if i have the same issue

Company Communicator (Author) send itself a message .zip to the app owner teams,  if you click on Accept, automatically file will be downloaded

**Comment by hunaidhanfee20** [comment] 2021-05-27 07:41
Hello @jcsul,
If the issue is related to recipient not visible in the list(see below screenshot attached) then you should check if user app is installed in the team where you are trying to send the message.
![image](https://user-images.githubusercontent.com/64194049/119785512-e2b4ef80-beec-11eb-8f86-f6d4e1ebd9d0.png)


There issue already raised related to **The bot is not part of the conversation roster**   #362 .
We are closing this one.

Thanks.

**Closed** 2021-05-27 12:01 UTC
