### ISSUE TITLE
Failed to sync all users. Status Code: Unauthorized Exception: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established

### ISSUE THREAD

**Issue by ramu-yarru** [OfficeDev/microsoft-teams-apps-company-communicator#826] opened 2022-08-06 17:25 UTC
I have successfully deployed the company communicator using powershell and I didn't face any issues/errors during deployment. But when I try to send message using author app, I am getting the following error.
Can someone please help/guide on how to solve this issue. 

Results
Success : 0
Failure : 0

Failed to sync all users. Status Code: Unauthorized Exception: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established.

**Comment by gsv022** [comment] 2022-08-08 09:16
Hi @ramu-yarru ,

Can you check if the client secret you provided in your app service and/or Key Vault is the same as what you got from your app registration? From the error message, the secret provided may be 1) incorrect or 2) expired. Below are the steps to check if the client secret is expired or not, if expired provided the steps how to create newly and update it, please let me know if you've any follow up questions.

1. To find author bot app id, go to Azure portal -> look for Company Communicator App services -> Configuration -> Author AppId

![image](https://user-images.githubusercontent.com/98143492/183382518-6d5d30f4-a2a3-44c7-8541-ce01ebc6939f.png)
 2. Click show values and copy the Id. 
 3. Go to App Registration and search for the app with id you copied above. 

4.Go the author app registration -> Certificates & secrets -> Check for expiry date of the secret

![image](https://user-images.githubusercontent.com/98143492/183382796-b77d6a10-3f65-42c4-917c-fcb5adf2343e.png)

5.  If the secret is already expired, click ‘New client secret’ and generate it

6. Copy the value, navigate to the Azure key vault for Company Communicator -> Secrets -> update the AuthorAppPassword

![image](https://user-images.githubusercontent.com/98143492/183382960-973e2847-42c2-49dd-8ae4-e6f5175ae8de.png)

7. Restart the app services, function apps.

**Comment by ramu-yarru** [comment] 2022-08-08 11:09
Hi [gsv022],

Thank you for your inputs. I verified the above secret and I can clearly see the secret is valid till 2023. It is correct secret only.
Btw, as I mentioned, I deployed the solution using powershell. Am I missing anything? Are there any additional steps to be configured?
![image](https://user-images.githubusercontent.com/34542224/183404763-cc1bcadc-bb13-4d0e-9454-b2e2fd2532a8.png)

**Comment by gsv022** [comment] 2022-08-08 11:32
@ramu-yarru , Just to re-iterate "Could you please cross-verify the setup authentication steps are already cleared in the script or not."

Please confirm on this.

**Comment by ramu-yarru** [comment] 2022-08-08 11:44
Hi gsv022,

Could you please elaborate on setup authentication steps.
I simply followed the powershell deployment steps listed in below link.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-powershell

Also, provide my Azure admin user accout details twice when prompted. Also mine is not certificate based authentication. So provided the following details in the JSON along with other details. 

"useCertificate": {
    "Value": false,
    "Description": "If certificate authentication is being used, then value should be true. Otherwise, false is default (Client-secret will be used)."
  },
  "authorAppCertName": {
    "Value": "<<value>>",
    "Description": "The X.509 certificate name of the author bot Azure AD app."
  },
  "graphAppCertName": {
    "Value": "<<value>>",
    "Description": "The X.509 certificate name of the Microsoft Azure AD app."
  },
  "userAppCertName": {
    "Value": "<<value>>",
    "Description": "The X.509 certificate name of the user bot Azure AD app."
  },

**Comment by v-royavinash** [comment] 2022-08-08 16:21
@ramu-yarru Did the PowerShell deployment without any errors? If yes, will it be possible to share the screenshot of logs which state deployment completed and no error was logged?

**Comment by ramu-yarru** [comment] 2022-08-08 16:59
Hi,

PFB screenshots.
![image](https://user-images.githubusercontent.com/34542224/183472562-3bb16d3d-92cc-4fb0-a36a-0d17cf87f97e.png)

![image](https://user-images.githubusercontent.com/34542224/183472657-202dbfd4-cc6d-4b0e-85f9-9864c9db413b.png)

![image](https://user-images.githubusercontent.com/34542224/183472757-84574a72-c1fa-4bf1-80bf-2e72f07db1c4.png)

**Comment by v-royavinash** [comment] 2022-08-08 17:43
@ramu-yarru We are closing the request as the issue is resolved.

Resolution steps:
-	Admin consent for Graph app permission was missing.
-	Deleted the by default field added in the expose an API of graph app.

**Closed** 2022-08-08 17:51 UTC
Labels: Needs: author feedback
