### ISSUE TITLE
Owners aren't getting broadcasts

### ISSUE THREAD

**Issue by BattleAxeNelson22** [OfficeDev/microsoft-teams-apps-company-communicator#663] opened 2022-03-09 21:06 UTC
When sending chat to 'members of following teams' or 'members of M365 groups' people who are listed as owners of those groups and not members are not getting broadcasts.

**Comment by gsv022** [comment] 2022-03-10 05:15
Hi @BattleAxeNelson22 ,

We will check the behavior and confirm this.

**Comment by gsv022** [comment] 2022-03-10 13:58
Hi @BattleAxeNelson22 ,
Observation 1:
If you are sending the message to teams channel, both members and owner will be receiving the message.

Observation 2:
For distribution lists(DL) and MS365, only the members will receive the message but not the owner.

We are reviewing this issue at code level but for now the workaround is to add the owners email to the members list so that they will be able to receive the messages.

**Comment by gsv022** [comment] 2022-03-31 12:25
Hi @BattleAxeNelson22 ,
Could you please confirm if the issue is resolved by following the work around steps and we are good to close this?

**Closed** 2022-04-04 09:41 UTC
Labels: answered, Needs: author feedback
