### ISSUE TITLE
When message was sent through the authors app, the results show success:0, Failure:0

### ISSUE THREAD

**Issue by sailekhya12cc** [OfficeDev/microsoft-teams-apps-company-communicator#620] opened 2022-02-01 13:13 UTC
We have installed the app following the instructions in manual deployment guide https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide. While testing it we are facing this issue
![cc message not sent](https://user-images.githubusercontent.com/98821141/151974805-c90d20a5-45ac-4f7b-8a9f-fd382d1fe466.jpg)
.

**Comment by v-royavinash** [comment] 2022-02-01 14:55
Hi @sailekhya12cc , There might be multiple reason for causing this issue. Can you please share the application insights logs for further troubleshooting?

Also please make sure the secrets are correctly copied and updated for the app service.

**Comment by sailekhya12cc** [comment] 2022-02-01 15:09
Hello Royavinash,

I would really appreciate if you could guide me how to collect application insights logs.

Thank you,
Sai Lekhya.
From: v-royavinash ***@***.***>
Sent: Tuesday, February 1, 2022 8:26 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Sai Lekhya Kancham ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

Hi @sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SxJ%2BnrlXHKasjpFbX242oYY%2BYtWccAz1WnROT0fpHPs%3D&reserved=0> , There might be multiple reason for causing this issue. Can you please share the application insights logs for further troubleshooting?

Also please make sure the secrets are correctly copied and updated for the app service.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1026930277&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UV%2BtTe87NH2VOXTbC751Op5BYwi0rqmUOebNicqjWdE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFOV73K4KED5I5P3ID3UY7X7TANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8ZIoMGdmOLh5EALpa%2BhB3hV1UdprkRCik9LUr0JSTQw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BZt75ogsc8DawjkJ2%2B5ADFDCsYyJZzsKTPSRtqmrLAQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566229928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qo3xuyGTkQ%2B1W41gaZO3OkXg6%2BYCR1Nj9vokuvi%2Bt7c%3D&reserved=0>.

**Comment by sailekhya12cc** [comment] 2022-02-03 13:09
++ Saranya from my team.

From: Sai Lekhya Kancham
Sent: Tuesday, February 1, 2022 8:39 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)

Hello Royavinash,

I would really appreciate if you could guide me how to collect application insights logs.

Thank you,
Sai Lekhya.
From: v-royavinash ***@***.******@***.***>>
Sent: Tuesday, February 1, 2022 8:26 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Sai Lekhya Kancham ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

Hi @sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SxJ%2BnrlXHKasjpFbX242oYY%2BYtWccAz1WnROT0fpHPs%3D&reserved=0> , There might be multiple reason for causing this issue. Can you please share the application insights logs for further troubleshooting?

Also please make sure the secrets are correctly copied and updated for the app service.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1026930277&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UV%2BtTe87NH2VOXTbC751Op5BYwi0rqmUOebNicqjWdE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFOV73K4KED5I5P3ID3UY7X7TANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8ZIoMGdmOLh5EALpa%2BhB3hV1UdprkRCik9LUr0JSTQw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BZt75ogsc8DawjkJ2%2B5ADFDCsYyJZzsKTPSRtqmrLAQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566229928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qo3xuyGTkQ%2B1W41gaZO3OkXg6%2BYCR1Nj9vokuvi%2Bt7c%3D&reserved=0>.

**Comment by sailekhya12cc** [comment] 2022-02-03 13:21
Hello Royavinash,

Attached the application insights logs.

Thank you,
Sai Lekhya.
From: v-royavinash ***@***.***>
Sent: Tuesday, February 1, 2022 8:26 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Sai Lekhya Kancham ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

Hi @sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SxJ%2BnrlXHKasjpFbX242oYY%2BYtWccAz1WnROT0fpHPs%3D&reserved=0> , There might be multiple reason for causing this issue. Can you please share the application insights logs for further troubleshooting?

Also please make sure the secrets are correctly copied and updated for the app service.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1026930277&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UV%2BtTe87NH2VOXTbC751Op5BYwi0rqmUOebNicqjWdE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFOV73K4KED5I5P3ID3UY7X7TANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8ZIoMGdmOLh5EALpa%2BhB3hV1UdprkRCik9LUr0JSTQw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BZt75ogsc8DawjkJ2%2B5ADFDCsYyJZzsKTPSRtqmrLAQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566229928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qo3xuyGTkQ%2B1W41gaZO3OkXg6%2BYCR1Nj9vokuvi%2Bt7c%3D&reserved=0>.

**Comment by sailekhya12cc** [comment] 2022-02-07 16:25
Hello Royavinash,

Kindly provide us any updates regarding the issue.

Thank you,
Sai Lekhya.


From: Sai Lekhya Kancham
Sent: Thursday, February 3, 2022 6:52 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>; Saranya V ***@***.***>
Subject: RE: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)

Hello Royavinash,

Attached the application insights logs.

Thank you,
Sai Lekhya.
From: v-royavinash ***@***.******@***.***>>
Sent: Tuesday, February 1, 2022 8:26 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Sai Lekhya Kancham ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

Hi @sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SxJ%2BnrlXHKasjpFbX242oYY%2BYtWccAz1WnROT0fpHPs%3D&reserved=0> , There might be multiple reason for causing this issue. Can you please share the application insights logs for further troubleshooting?

Also please make sure the secrets are correctly copied and updated for the app service.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1026930277&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UV%2BtTe87NH2VOXTbC751Op5BYwi0rqmUOebNicqjWdE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFOV73K4KED5I5P3ID3UY7X7TANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8ZIoMGdmOLh5EALpa%2BhB3hV1UdprkRCik9LUr0JSTQw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566073697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BZt75ogsc8DawjkJ2%2B5ADFDCsYyJZzsKTPSRtqmrLAQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C400e2527442744fef12108d9e592f29d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637793241566229928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qo3xuyGTkQ%2B1W41gaZO3OkXg6%2BYCR1Nj9vokuvi%2Bt7c%3D&reserved=0>.

**Comment by v-royavinash** [comment] 2022-02-08 11:12
@sailekhya12cc , We could not find the app insights log shared. Are you available over MS Teams? If yes, please share your account alias?

**Comment by sailekhya12cc** [comment] 2022-02-08 11:15
Hello Royavinash,

Thank you for your response.
I am available in ms teams and you can ping me there my id: ***@***.***

Thank you,
Sai Lekhya.


From: v-royavinash ***@***.***>
Sent: Tuesday, February 8, 2022 4:43 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Sai Lekhya Kancham ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

@sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7Cdebc0de2e60f4b7f2a3408d9eaf3e932%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799155589771071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wIWQoAc4OdfewFe1DlIRLEdNFxMwtU9SzP3i%2BW7b3sU%3D&reserved=0> , We could not find the app insights log shared. Are you available over MS Teams? If yes, please share your account alias?

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1032491249&data=04%7C01%7Csailekhya.kancham%40nxp.com%7Cdebc0de2e60f4b7f2a3408d9eaf3e932%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799155589771071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jmskiO3qRtzIFFfmmawEiu82%2FJZDttaMBKicjASzGA4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFKQW3PTQNTPET33VGTU2D3CFANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7Cdebc0de2e60f4b7f2a3408d9eaf3e932%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799155589771071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jFyfdTGwPnq4qLshh57SDvuhhDSCfhRASFmRVLrjP6Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7Cdebc0de2e60f4b7f2a3408d9eaf3e932%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799155589771071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vZeW%2BHPOFT4nfMsBNCgYZsYEOw%2BUNmYuDyTul2RJ6OU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7Cdebc0de2e60f4b7f2a3408d9eaf3e932%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799155589771071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xFjTbI4M3lLsV9oOpIRbhRnw7apWWWJ2P20ydPvSdK8%3D&reserved=0>.

**Comment by sailekhya12cc** [comment] 2022-02-08 12:45
Hello Royavinash,

Attached  the application logs.

Thank you,
Sai Lekhya.
From: v-royavinash ***@***.***>
Sent: Tuesday, February 8, 2022 4:59 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Sai Lekhya Kancham ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-company-communicator] When message was sent through the authors app, the results show success:0, Failure:0 (Issue #620)


Caution: EXT Email

@sailekhya12cc<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsailekhya12cc&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C76fafb448e8242d1683008d9eaf62d08%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799165299626978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OIbOCsXqq70BMFLpvqKFzUynMq%2B%2BAvEzlYAbXWYfH4E%3D&reserved=0> , We are not able to view your Id. Can you please share the app insights logs?

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F620%23issuecomment-1032505938&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C76fafb448e8242d1683008d9eaf62d08%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799165299626978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iwOGLyOTz1mVCHc2%2BaUJOCTqSzFeA8%2BOaIxXxLqSFPs%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXR6IFLWLMQX6XNGJGYA25DU2D467ANCNFSM5NJDPZXQ&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C76fafb448e8242d1683008d9eaf62d08%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799165299626978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LRQG%2BwjYCozu4etaUknjsRc03cSCtS1o2IcrPV8exgg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C76fafb448e8242d1683008d9eaf62d08%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799165299626978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s%2BFzIlDfenhxmyZxAWJqCvzhVYi0cyhceLV4Gpufe0E%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csailekhya.kancham%40nxp.com%7C76fafb448e8242d1683008d9eaf62d08%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637799165299626978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dI1vZNZBx4uRNJkTWKM96mmQa0UoVyM41aSv7ftm8rg%3D&reserved=0>.

**Comment by sailekhya12cc** [comment] 2022-02-09 05:45
Hi @v-royavinash ,
Please find attached file and do the needful. Also let us know if we can have call by any means if you dont find us via Teams.

[query_data.csv](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8029823/query_data.csv)

**Comment by v-royavinash** [comment] 2022-02-09 10:42
Hi @sailekhya12cc ,

The logs shared are not much of helpful as its doesn't have any errors listed.  Could you please share of MS Teams alias? The previously shared alias was in hidden format.

![image](https://user-images.githubusercontent.com/94480537/153181822-58cc05ec-9ada-4ab0-8e21-7d5c7417a49f.png)

**Comment by sailekhya12cc** [comment] 2022-02-09 11:35
Hi @v-royavinash ,
Kindly reach me via MS Teams - email address: vsaranya27@gmail.com

**Comment by gsv022** [comment] 2022-04-05 07:53
Hi @sailekhya12cc ,
Could you please confirm whether the issue is closed or not?

**Comment by gsv022** [comment] 2022-04-07 06:12
Hi @sailekhya12cc ,
We are closing the issue request. Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.

**Closed by gsv022** 2022-04-07 06:12 UTC
Labels: details needed
