### ISSUE TITLE
ARM template deployment error

### ISSUE THREAD

**Issue by MSPFE2019** [OfficeDev/microsoft-teams-apps-company-communicator#563] opened 2021-11-30 18:36 UTC
I am not sure what I am getting this error, can you please help me figure this out?

Error occurred while deploying Azure resources.
ERROR: ARM template deployment error.
At C:\microsoft-teams-apps-company-communicator-master\microsoft-teams-apps-company-communicator-master\Deployment\depl
oy.ps1:530 char:17
+                 Throw $deploymentExceptionMessage
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ERROR: ARM template deployment error.:String) [], RuntimeException
    + FullyQualifiedErrorId : ERROR: ARM template deployment erro
[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/7627983/logs.zip)
r.

**Comment by MSPFE2019** [comment] 2021-12-01 03:07
@Porkai-Pandian thank yo, that was the issues. I need to delete all components and start over to get it work.

**Comment by Porkai-Pandian** [comment] 2021-12-01 05:14
Hi @MSPFE2019,

Thanks for the confirmation and glad that the issue is resolved, we'll proceed with closing the bug

**Closed by Porkai-Pandian** 2021-12-01 05:14 UTC
