### ISSUE TITLE
Failed to sync all users. Status Code: 0  | An error occurred while sending the request.

### ISSUE THREAD

**Issue by CarlosGuadamuz** [OfficeDev/microsoft-teams-apps-company-communicator#784] opened 2022-06-24 21:13 UTC
Sending communications is taking more than 24 hours for just 1200 users.

Date: 06-21-2022 09:00 a.m.

Failed to sync all users. Status Code: 0 Exception: Code: GeneralException Message: An error occurred while sending the request.

**Comment by gsv022** [comment] 2022-06-27 06:02
Hi @CarlosGuadamuz ,
We will reach out over the teams and troubleshoot the issue soon. 
Thank you.

**Comment by v-royavinash** [comment] 2022-06-28 21:32
@CarlosGuadamuz Closing the request as the issue is fixed. The secrets were expired and we updated the configuration with newly generated secrets.

**Closed by v-royavinash** 2022-06-28 21:32 UTC
Labels: Needs: triage :mag:
