### ISSUE TITLE
User Reactions - How to get the NotificationId ?

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/microsoft-teams-apps-company-communicator#531] opened 2021-10-27 14:51 UTC
Hi,
I am almost there to capture the user reactions. The code is as follows.
Can someone help me on how to get the `notificationid`?

In the `Bot/UserTeamsActivityHandler` I have below code.

```
protected override async Task OnMessageReactionActivityAsync(
	ITurnContext<IMessageReactionActivity> turnContext,
	CancellationToken cancellationToken)
{
	await base.OnMessageReactionActivityAsync(turnContext, cancellationToken);

	NotificationDataEntity notificationDataEntity = await this.notificationDataRepository.GetAsync(
		NotificationDataTableNames.SentNotificationsPartition,
		"<NOTIFICATION-ID>");

	if (notificationDataEntity == null)
	{
		return;
	}

	if (turnContext.Activity.ReactionsAdded != null)
	{
		notificationDataEntity.Reactions++;
		await this.notificationDataRepository.CreateOrUpdateAsync(notificationDataEntity);
	}
	else if (turnContext.Activity.ReactionsRemoved != null)
	{
		notificationDataEntity.Reactions--;
		await this.notificationDataRepository.CreateOrUpdateAsync(notificationDataEntity);
	}
}
```

**Comment by cristianoag** [comment] 2021-11-05 05:04
Hello @nanddeepn. I did some analysis and here is my observations:

1. CC stores an internal message id on the PartitionKey. That message id is not the same of the ID used by teams, it is just a way to track the notification internally. 
2. The SentNotificationData table stores the conversation id so every notification sent to a specific user is kept in the same chat in Teams. 
3. I couldn't find a way to access the Activity.Attachments object of the Activity users are reacting to. The Attachment of the original message has all data we need, including the internal CC message id.
4. Even not finding the relationship between ids in Teams and CC, we can track down messages sent using the conversation id we have. The problem is that you will get all messages sent in that specific conversation, not just the message where the user reacted.

You can use the code below to understand how to get the Conversation ID. With it you can search and update the SentNotificationData table.

protected override async Task OnMessageReactionActivityAsync(
            ITurnContext<IMessageReactionActivity> turnContext,
            CancellationToken cancellationToken)
        {
            await base.OnMessageReactionActivityAsync(turnContext, cancellationToken);

            string newReaction = $"You reacted with to the following message: '{turnContext.Activity.ReplyToId}' in the conversation ID: '{turnContext.Activity.Conversation.Id}'.";
            Activity replyActivity = MessageFactory.Text(newReaction);
            await turnContext.SendActivityAsync(replyActivity, cancellationToken);
        }

**Comment by cristianoag** [comment] 2021-11-05 05:05
I'll invest a bit more time next week trying to get the Activity where the user reacted.

**Comment by nanddeepn** [comment] 2021-11-05 08:48
Hi @cristianoag 
Thank you for your inputs. I am also looking at possible way to get the notificationid.

One thing I came across is, we can pass custom properties to `ChannelData`. However, it is only available for channel messages and not for the personal messages.

**Comment by v-royavinash** [comment] 2022-07-26 00:26
@nanddeepn  we're closing this issue since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.

**Closed by v-royavinash** 2022-07-26 00:26 UTC
Labels: enhancement
