### ISSUE TITLE
A case of resolving the message pending in sending for users' reference

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [OfficeDev/microsoft-teams-apps-company-communicator#588] opened 2021-12-22 08:11 UTC
**Issue Description**
Recently an user David Liong was facing an issue that the Communicator App stuck when sending messages as below.
![image](https://user-images.githubusercontent.com/45751478/147057609-d6f2455b-548a-415c-8933-bb5c78b5402f.png)

**Resolution**
1.The user changed the Bot App register's client secret due to the expiration.
![image](https://user-images.githubusercontent.com/45751478/147057818-c522d569-5c40-4cdd-a50d-da97fa03946e.png)

2.The user updated the client secret password for the app in the app service config settings. Then the stuck issue happened.
3.The user found there was a config setting variable MicrosoftAppPassword that didn’t update with the new client secret in app service.
4.The config setting variable MicrosoftAppPassword was also in 3 function apps config settings as well.
![image](https://user-images.githubusercontent.com/45751478/147058270-d83326bd-c869-4fb3-beaa-8e9ee75efa43.png)

5.The user updated each function app config settings with new client secret password and restart each function app.
6.Then the posted message that was in queue was able to be posted and sent to everyone in the organization.

**Comment by v-royavinash** [comment] 2021-12-22 10:27
Thanks, @AlexChongMicrosoft  for the issue and resolution step. Closing the issue as the issue is resolved with the steps mentioned.

**Closed by v-royavinash** 2021-12-22 10:27 UTC
