### ISSUE TITLE
The activity function 'StoreMessageActivity' failed:

### ISSUE THREAD

**Issue by acanton5** [OfficeDev/microsoft-teams-apps-company-communicator#560] opened 2021-11-25 17:55 UTC
Dear team,

I get this error:

Failed to prepare the message for sending: The activity function 'StoreMessageActivity' failed: "Invalid URI: The hostname could not be parsed.". See the function execution logs for additional details.

do you know anything about it?

**version 5**

Kind regards,
Alexander

**Comment by Porkai-Pandian** [comment] 2021-11-29 18:41
Hi @acanton5,

Thank you for raising the query, issue seems to be in your xxxx-prep-function, please check your configuration in the prep function to make sure the URI's updated are correct, if so you can check the logs in Application insights for more information.

**Comment by acanton5** [comment] 2021-11-30 15:44
Hello,
you mean here? I don't see any URI value. Just KeyVault:Url.

![image](https://user-images.githubusercontent.com/73191514/144079346-a4b6aae9-95da-4379-86ec-a4234ab2a748.png)

**Comment by acanton5** [comment] 2021-12-13 15:36
Hello @Porkai-Pandian can you help here?

**Comment by Porkai-Pandian** [comment] 2022-02-15 18:34
Worked over the call with customer and issue is resolved as confirmed with customer, hence closing the issue

**Closed by Porkai-Pandian** 2022-02-15 18:34 UTC
