### ISSUE TITLE
Deployment stuck on Running

### ISSUE THREAD

**Issue by def1nity** [OfficeDev/microsoft-teams-apps-company-communicator#641] opened 2022-02-16 07:53 UTC
Hello,

I'm testing the deployment of the app but it's getting stuck on this step:
"Deploying app services, Azure function, bot service, and other supporting resources... (this step can take over an hour)
 - Running .."

It is spinning but even after leaving it overnight there is no progress.

There are no logs I could find and I also tried running the ps1 with --debug to no avail. It is the same when choosing entirely new names and when overwriting existing ones.

Could someone assist in how to troubleshoot this?

Thanks

> .\deploy.ps1 --debug
> Checking if Azure CLI is installed.
> Azure CLI is installed.
> Checking if the required modules are installed...
> Az module is available.
> AzureAD module is available.
> WriteAscii module is available.
> All the modules are available!
> Validating all the parameters from parameters.json
> Starting deployment...
> Login with with your Azure subscription account. Launching Azure sign-in window...
> 
> WARNING: The default web browser has been opened at https://login.microsoftonline.com/2690ea74-0323-48f1-84d1-26bab8f950b4/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
> WARNING: You have logged in. Now let us find all the subscriptions to which you have access...
> Azure AD sign-in...
> Checking for resources availability...
> resource: CompanyCommunicator of type webapp is available.
> resource CompanyCommunicator-data-function is not available.
> Hostname 'CompanyCommunicator-data-function' already exists. Please select a different name.
> resource CompanyCommunicator-function is not available.
> Hostname 'CompanyCommunicator-function' already exists. Please select a different name.
> resource CompanyCommunicator-prep-function is not available.
> Hostname 'CompanyCommunicator-prep-function' already exists. Please select a different name.
> Application Insights resource (CompanyCommunicator) is available.
> 
> Some of the resource types names already exist. If you proceed, this will update the existing resources.
> Do you want to proceed?
> [Y] yes  [N] no  [?] Help (default is "N"): y
> 
> Creating Azure AD App: CompanyCommunicator-users...
> 
> The Azure AD app 'CompanyCommunicator-users' already exists. If you proceed, this will update the existing app
> configuration.
> Do you want to proceed?
> [Y] Yes  [N] No  [?] Help (default is "N"): y
> Updating the existing app...
> Waiting for app update to finish...
> Azure AD App: CompanyCommunicator-users is updated.
> Updating app secret...
> WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
> Azure AD App: CompanyCommunicator-users registered successfully.
> 
> Creating Azure AD App: CompanyCommunicator-authors...
> 
> The Azure AD app 'CompanyCommunicator-authors' already exists. If you proceed, this will update the existing app
> configuration.
> Do you want to proceed?
> [Y] Yes  [N] No  [?] Help (default is "N"): y
> Updating the existing app...
> Waiting for app update to finish...
> Azure AD App: CompanyCommunicator-authors is updated.
> Updating app secret...
> WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
> Azure AD App: CompanyCommunicator-authors registered successfully.
> 
> Creating Azure AD App: CompanyCommunicator...
> 
> The Azure AD app 'CompanyCommunicator' already exists. If you proceed, this will update the existing app configuration.
> Do you want to proceed?
> [Y] Yes  [N] No  [?] Help (default is "N"): y
> Updating the existing app...
> Waiting for app update to finish...
> Azure AD App: CompanyCommunicator is updated.
> Updating app secret...
> WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
> Azure AD App: CompanyCommunicator registered successfully.
> Creating resource group CompanyCommunicatorRG...
> 
> Deploying app services, Azure function, bot service, and other supporting resources... (this step can take over an hour)
>  - Running ..

**Comment by Porkai-Pandian** [comment] 2022-02-17 01:26
Hi @def1nity,

Thank you for letting us know of the issue you're facing, please re-try the deployment in case of failures as mentioned in the deployment guide. If you've already retried multiple times, I suggest trying the deployment manually.

**Comment by def1nity** [comment] 2022-02-17 12:36
Hi @Porkai-Pandian 

Thank you for the reply. Re-trying the deployment did not help. 

I was able to locate the issue after digging around in the azure subscription. I noticed the deployment was failing for the resource group with error 429: App Service Plan Create operation is throttled for subscription <subscription-id>. Please contact support if issue persists.

Apparently as I am using the Basic tier and had to re-run the ps1 script a couple of times in the beginning until every plugin was installed and I guess around that time I hit the app service creation limit.

Solution was to switch to a different region and define new RG and app names. 

May I suggest to include some sort of a switch when running the deploy.ps1 which will yield a bit more details for the current step? As it stands PS script was "Running" but actually was just waiting for never-ending "retry-after" time outs.

Thanks!

**Comment by gsv022** [comment] 2022-03-31 12:48
Hi @def1nity,
You can view the run time deployment logs of the deploy.ps1 by going to App Service --> Deployment Center --> Logs and there will be a clickable entry under logs.
On click of the link, you can view the script execution. Also we recommend to use S2 instance for app service plan.
As the issue is already fixed we are closing the request.

**Closed** 2022-03-31 12:48 UTC
