### ISSUE TITLE
About bug that cannot be received due to chat deletion

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#954] opened 2023-01-16 09:34 UTC
Hi,
I have a question about the bug mentioned in thread #941.

Q1.
Is there a way for the sender to check the result that the message could not be received?
I'm worried that users who deleted chats don't realize they didn't receive the message.

Q2.
Does this happen only for chats received from CC?
If I delete the sender's chat, does the history just disappear?

Regards,
(CC: @ATshirai)

**Comment by gsv022** [comment] 2023-01-17 06:57
Hi @MK202204 ,
Thanks for raising the query. 

- _Is there a way for the sender to check the result that the message could not be received?_
 -->yes, this is a bug. Users who deleted chat will not be receiving the messages further.

- _If I delete the sender's chat, does the history just disappear?_
 -->If we understood correctly, sender's chat  i.e., author app once the chat is deleted then history will get disappeared.

Please let us know if you have any queries.

**Comment by MK202204** [comment] 2023-01-18 07:08
Hi @gsv022 
Thankyou for your reply.

I have an additional question.
Is there a way to find out who deleted a chat?
and Does this issue occur in ver.4.1?

Regards,

**Comment by gsv022** [comment] 2023-01-24 08:29
Hi @MK202204 ,
Thanks for the patience. Here is the update.
_For **5.x version**_,
-  Both author and user app(one after the another), manually cc chat is deleted and again when the author sends a message sender/user for whom the cc chat was deleted they were able to receive the new messages but previous messages were getting cleared. Hence the bug is not observed and working fine.

_For **4.x version**_ 

- Both author and user app  , manually cc chat is deleted and again when the author sends a message sender/user for whom the cc chat was deleted they were able to receive the new messages but previous messages were getting cleared. Hence the bug is not observed and working fine.

Could you please respond to the below queries.

- For which version of the app, the issue has been observed
- **_I'm worried that users who deleted chats don't realize they didn't receive the message._**,  if you have tried this scenario can you confirm on the user presence in the team. Here is the reference.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/98143492/214241340-2dbe0ca3-2d71-4ea8-9f1a-14b690e70ba4.png">

- The reason for asking the above point is we doubt that once the user deletes the cc chat, he/she not only receive messages but also getting removed from the team. If this is the case then it is something happening at the teams platform.

**Comment by MK202204** [comment] 2023-01-24 09:24
@gsv022 
Thank you for your reply.

Does it mean that No bugs were found as a result of your operation check?
I didn't get an inquiry from a user, But I read #941 and thought there was a bug.
Am I correct in understanding that **#941 was not a bug**?

Best Regards,

**Comment by ATshirai** [comment] 2023-01-24 11:04
Hi @gsv022,

May I ask you about your test cases ?
The issue #941 used the feature of "send a message to everyone".  
On your test cases, what kinds of features were used?
Or did you try all ones?

**Comment by v-royavinash** [comment] 2023-03-08 00:05
@MK202204 , We have marked the behavior as designed, and we will revisit the behavior of Company Communicator once the user deletes the chat. Currently, we are working on other priority features, and depending backlog priority, we will test and accommodate the chat deletion behavior of CC.

If you experience any issues with the deployment of Company Communicator or encounter problems sending messages, we kindly request that you log a new issue.

**Comment by v-royavinash** [comment] 2023-06-12 21:40
@MK202204 We are closing this issue as the feature has already been added to our backlog. It will be considered for future releases of CC based on its priority.

**Closed** 2023-06-20 07:01 UTC
Labels: enhancement, Needs: author feedback, Status: no recent activity
