### ISSUE TITLE
Permissions error - company communicator

### ISSUE THREAD

**Issue by Sammy7862** [OfficeDev/microsoft-teams-apps-company-communicator#674] opened 2022-03-22 11:08 UTC
![image](https://user-images.githubusercontent.com/93075310/159468104-846e0b08-4526-4967-a05b-917b53d5eecf.png)
![image](https://user-images.githubusercontent.com/93075310/159468302-c4363404-e12f-4f8e-b65b-3626950ac1dc.png)

I am an author for the company communicator app but keep getting permissions error. Please can you help/advise?

**Comment by gsv022** [comment] 2022-03-22 13:35
Hi @Sammy7862 ,
Can you please check if your id has been added to the UPN list during the deployment.
To check this. Follow these steps:

- 	Navigate to Azure portal and open company communicator deployed resource group
- 	Click on “App service”
- 	Click on “Configuration” in left navigation
- 	Click on “AuthorizedCreatorUpns” and check if you are id has been added. If not, update the value with required authors UPN (semicolon separated).
- 	Click on “Ok” .
- 	Click on “Save” and Continue.

**Comment by Sammy7862** [comment] 2022-03-22 14:59
Please can you provide screenshots of the steps? Thanks

**Comment by Sammy7862** [comment] 2022-03-23 09:37
I manage to update the AuthorizedCreatorUpns and the permissions is working now but when creating a new message there is no option to select other teams where the company communicator is added. I noticed an error in the deployment - microsoft template withing the resource group.


[MSTemplate error.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8331744/MSTemplate.error.txt)

![image](https://user-images.githubusercontent.com/93075310/159668757-fe4a4854-73ac-45e1-be1a-087ffb6c8bb8.png)

![image](https://user-images.githubusercontent.com/93075310/159668902-f6c56263-5ba3-4c04-b5ef-3fb2287965ac.png)


Please can you help?

**Comment by gsv022** [comment] 2022-03-23 11:21
Hi @Sammy7862 ,
As per the logs, the deployment failed for one of the resources due to Gateway error. 
Could you please share the screen shot of entire deployment logs to confirm which resource failed. Also if, the resource failed is either App Service or one of the Azure functions, please
 go to the **failed resource** --> **Deployment center** and click on **Sync** to re-deploy the failed resource.

**Comment by Sammy7862** [comment] 2022-03-23 12:01
![image](https://user-images.githubusercontent.com/93075310/159694143-20a75e68-01a7-4eb7-be9b-62bd2cd3b2ed.png)
[failed deployment logs.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8332762/failed.deployment.logs.txt)

**Comment by gsv022** [comment] 2022-03-23 13:20
Hi @Sammy7862 ,
Please re-deploy the App service. 
Go to **Deployment center** and click on **Sync** to re-deploy the failed resource.

**Comment by gsv022** [comment] 2022-03-31 05:57
Hi @Sammy7862,
Could you please confirm if the issue is resolved after re-deploying the App service and we are good to close this?

**Comment by v-royavinash** [comment] 2022-04-04 09:39
We are closing out the issue.

**Closed by v-royavinash** 2022-04-04 09:39 UTC
Labels: answered, Needs: author feedback

**Comment by Sammy7862** [comment] 2022-04-05 06:33
It seems to be working however, when adding company communicator to another team, I cannot view that team the company communicator has been added to so I can post message to that particular team, for example a team named Global-IT-Service-Collaboration cannot see IT TEST TEAM to post message to. Both teams have the company communicator app deployed.

**Comment by Sammy7862** [comment] 2022-04-05 11:38
![image](https://user-images.githubusercontent.com/93075310/161745615-a6387595-c734-449d-8e3c-62bcc267d01d.png)
![image](https://user-images.githubusercontent.com/93075310/161745816-f160624b-f953-4700-9af7-0e73b6876329.png)
