### ISSUE TITLE
Status Reports are not getting downloaded by Authors

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-apps-company-communicator#234] opened 2020-11-05 11:18 UTC
Dear Team,

Company Communicator Authors are unable to download the Status Reports. Please let me know the solution, Senior Leadership team are using this and its not working for them need your assistance.

Below is the Screenshot when I try to download it gives error says company communicator does not supports files. Old downloaded data also sends repeated alerts as message expired. Is there any way to stop those.

![image](https://user-images.githubusercontent.com/71570629/98234765-e6038080-1f86-11eb-8e30-07d41606408a.png)

**Comment by bungleweed** [comment] 2020-11-06 20:27
Getting the same issue after upgrading to v3. API permissions look correct based on the new one required.

**Comment by bungleweed** [comment] 2020-11-06 20:43
I think the issue is in the manifest.json for the end users app under the bots area supports files is set to false.

**Comment by bungleweed** [comment] 2020-11-06 20:44
I'd set it to true, increment the version, rezip and update the app.

**Comment by Sheshank-TCS** [comment] 2020-11-24 15:56
@bungleweed  -  the authors app under the bots area supports files is set to True. It still the same issue. Can this be resolved without a version upgrade. As I am not sure if version upgrade in production is a good idea. Can you let me know if Microsoft Support can assist on call for version upgrade.

**Comment by juna-gupta** [comment] 2020-12-01 14:12
@Sheshank-TCS If you update the author application, its only the authors who will get the update. Could you try and let us know if that resolves the issue?

We are planning to split bot for users (recipients) and authors in future updates.

**Comment by priyank29** [comment] 2021-06-12 12:27
@Sheshank-TCS this issue was fixed in release v4. please upgrade to resolve this.

**Comment by priyank29** [comment] 2021-06-12 12:28
Please let us know if you still face the issue after upgrading the app.

**Closed by priyank29** 2021-06-12 12:28 UTC
Labels: bug
