### ISSUE TITLE
Fail to export excel for message sent result, and throw error "This card action is disabled because you've blocked"

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#967] opened 2023-02-14 10:08 UTC
Following error "This card action is disabled because you've blocked" prompt when I try to export the excel for message sent result, please kindly advise, thanks

<img width="316" alt="image" src="https://user-images.githubusercontent.com/25476072/218703947-6ea0cae1-9c66-4700-a7b1-115a89a34e70.png">

**Comment by gsv022** [comment] 2023-02-14 10:23
Hi @rex-ma ,
Thanks for raising the query. Could you please check the API permissions given correctly or not for graph app. Here is the reference.
<img width="789" alt="image" src="https://user-images.githubusercontent.com/98143492/218707837-3ae3cee3-71ed-4d31-a276-f0c81fe5052d.png">

**Comment by stashinskii** [comment] 2023-02-14 22:08
We noticed that this issue caused by misconfigured HTTP request sent from a Teams client (desktop, web, mobile).

Composed request missing `appName` query parameter (you can also notice that file consent card has "Unknown app" label)  and as a result, request resulting with `500 Internal Server Error`. 
Reproducing request manually with same JWT token and filled appName resulted with `200 OK` response.

I assume this issue is on Teams Service (API and/or client) and hopefully would get resolved soon 😊.

**Comment by angtany** [comment] 2023-02-16 15:50
@gsv022 Facing same issue, can you please guide the next steps

**Comment by cristianoag** [comment] 2023-02-16 15:54
Additional information on this issue. It looks like it is happening just in specific regions. I have a deployment on the Amer-02 region working just fine and another in Apac-02 performing posts against the Teams API without the name of the App. @angtany and @rex-ma, can you confirm if you both are running from Apac-02?

**Comment by gsv022** [comment] 2023-02-20 08:28
@rex-ma , Could you please let us know the status

**Comment by angtany** [comment] 2023-02-20 12:04
@cristianoag - I have deployment in West US region (App service) , still facing the same issue

**Comment by cristianoag** [comment] 2023-02-20 12:07
It looks like a deployment is being doing in all regions and adding the error condition. My deployments in americas now also don’t work anymore.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gp92** [comment] 2023-02-22 11:33
Same issue here in West Europe region. Almost 2 weeks facing this issue
![image](https://user-images.githubusercontent.com/5497444/220608349-d7138be4-fe35-410e-9909-00f79d8ac265.png)

**Comment by cristianoag** [comment] 2023-02-22 12:21
@gp92 is that a new deployment or the error appeared in a setup that was working previously?

**Comment by gp92** [comment] 2023-02-22 13:00
@cristianoag it is a setup that worked perfectly till 2 weeks ago (approximately). Honestly the export function is not something that we use regularly so I cannot be precise on the date when stopped working. Right now is quite important because we have an issue with a specific user which is not able to receive any communication despite months ago was able to which seems to be linked to another bug mentioned in the issues list  #956

**Comment by cristianoag** [comment] 2023-02-22 13:30
Meanwhile until the issue gets fixed you can get the information you need from the database. Just look on the sent notifications table.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by angtany** [comment] 2023-02-23 12:17
@gp92  Also you can get exported csv files from Azure blob by navigating on the below path - 
CC Resource Group -> Storage Account -> Containers (Blob Containers) -> Export Data blob -> here, all the csv files (that you are trying to export) reside.

**Comment by fajr365** [comment] 2023-03-03 15:19
> Hi @rex-ma , Thanks for raising the query. Could you please check the API permissions given correctly or not for graph app. Here is the reference. <img alt="image" width="789" src="https://user-images.githubusercontent.com/98143492/218707837-3ae3cee3-71ed-4d31-a276-f0c81fe5052d.png">

Where are these API Permissions? on the "App", "Author" or"User" App registration? I have them set on the "App" and the following on the others
"Author" - user.Read
"User" - User.Read

**Comment by gp92** [comment] 2023-03-06 15:04
Hi @angtany, thanks for the hint! It is working perfectly.
In the meanwhile I would to ask to @cristianoag and @gsv022 if there are news on this or any other troubleshooting step

**Comment by rex-ma** [comment] 2023-03-06 18:33
> > Hi @rex-ma , Thanks for raising the query. Could you please check the API permissions given correctly or not for graph app. Here is the reference. <img alt="image" width="789" src="https://user-images.githubusercontent.com/98143492/218707837-3ae3cee3-71ed-4d31-a276-f0c81fe5052d.png">
> 
> Where are these API Permissions? on the "App", "Author" or"User" App registration? I have them set on the "App" and the following on the others "Author" - user.Read "User" - User.Read

Hi @fajr365 , I have checked the browser Dev Tools logs and confirmed the issue is Teams API error that mentioned by @cristianoag

**Comment by gragosto** [comment] 2023-03-10 18:23
> Following error "This card action is disabled because you've blocked" prompt when I try to export the excel for message sent result, please kindly advise, thanks
> 
> <img alt="image" width="316" src="https://user-images.githubusercontent.com/25476072/218703947-6ea0cae1-9c66-4700-a7b1-115a89a34e70.png">

Hi, I have also been impacted by this issue. When it will be resolved?

**Comment by gragosto** [comment] 2023-04-10 14:42
Hi I'm still seeing this error
<img width="341" alt="image" src="https://user-images.githubusercontent.com/117857208/230923997-e1826f2c-96e1-4b15-a20c-8333e3e1ec03.png">

Any advice on how to fix it?

**Comment by cristianoag** [comment] 2023-04-10 15:41
It looks like the problem only happens with authors that are no Global Admins. when using my global admin account, the file is exported, but normal authors cannot export it.

**Comment by gsv022** [comment] 2023-04-19 13:51
@rex-ma ,
Here is the workaround for the Export issue.

- Go to Azure Portal

- Click on the resource group that has been used for CC

- Go to Storage Account.

- Select Storage browser

- Go to Blob Containers

- Click on export data blobs.

- Copy the desired zip folder name from teams and search for required zip folder in export data blobs.

- Click on the zip folder that needs to download

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Download the zip file.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Once the issue is resolved,  we will update you.

**Comment by danielmacedo90** [comment] 2023-04-26 16:41
Any update? We are facing the same problem.

**Comment by Fadel1949** [comment] 2023-05-03 03:52
From my observation, when I try to export via mobile, it can be export but when using desktop, it can't be export.

**Comment by vafzamora** [comment] 2023-05-11 19:07
> Hi I'm still seeing this error <img alt="image" width="341" src="https://user-images.githubusercontent.com/117857208/230923997-e1826f2c-96e1-4b15-a20c-8333e3e1ec03.png">
> 
> Any advice on how to fix it?

In my case the problem was solved publishing the CC Authors application to company catalog instead of side loading from the manifest. 

What Teams is trying to do is submit a POST to /api/mt/part/amer-03/beta/apps/files/file?fileName=myfile.zip&appName=&rootFolderName=Applications, and it's causing a 500 response because of the empty appName. 

The request will works when repeating it using Postman or whatever requesting tool. I don't know why the application name is not retrieved by the client when sideloading the app. 

Hope it helps,

**Comment by cristianoag** [comment] 2023-05-11 19:34
I've heard we have a fix being deployed as we speak. So, I expect the problem will go away to everybody as the deployment waves get completed.
________________________________

**Comment by gsv022** [comment] 2023-07-11 06:16
Hi @rex-ma ,
Thanks for the patience. The issue has been fixed by the concerned team. Please check and confirm the export functionality working status from your end.

Keep us posted

**Comment by Fadel1949** [comment] 2023-07-11 09:17
Hi @cristianoag ,
Have you updated your repositories ( https://github.com/cristianoag/microsoft-teams-apps-company-communicator ) regarding this issue?

**Comment by cristianoag** [comment] 2023-07-11 10:01
The problem was not caused by CC code it was an issue with the api. At least from what I know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2023-07-18 19:01 UTC
Labels: answered, Needs: author feedback, Status: no recent activity
