### ISSUE TITLE
Export status of sent messages

### ISSUE THREAD

**Issue by maye-vargas** [OfficeDev/microsoft-teams-apps-company-communicator#979] opened 2023-03-02 19:41 UTC
Good morning, could you help me, when I export the status of the messages, I get an error, when I give permission, it tells me that "The card is blocked or does not have permissions", and it does not allow me to authorize to save in my Onedrive, what could it be? Could you please help me?
![image](https://user-images.githubusercontent.com/86726190/222534880-26acae8c-97eb-48ad-bff1-62d7d254e5a5.png)

**Comment by gsv022** [comment] 2023-03-03 09:23
Hi @maye-vargas ,
Thanks for raising the query. Please respond to the below queries.

- What is the region that has been selected while creating ARM template?
- Please share the screenshot of graph app API permissions . Here is the reference.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/98143492/222682404-158612f8-66b2-44b2-b7d2-31c7509df80f.png">

- Could you please confirm whether you are able to send the messages through all sending options.

**Comment by maye-vargas** [comment] 2023-03-03 12:16
Good day,

- Where can I check the ARM region?
It is that I do not remember the region that was established.
- Subsequently, yes sir, the shipping theme works correctly in all possible shipments, with that theme I have not had any problems

As I already told you, the problem is allowing the state to be saved in the onedrive, but it only happens with the authors, the user who implemented the company, if allowed, but the other authors do not allow them to save and export it

**Comment by fajr365** [comment] 2023-03-03 15:10
I am having a simular issue, "This card action is disabled because you've blocked ." How do i remove the block?

**Comment by gsv022** [comment] 2023-03-06 06:28
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

--Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">

 -- Then select **inputs** from left section where you can find the  that are used. Please share them.
<img width="934" alt="image" src="https://user-images.githubusercontent.com/98143492/223035121-19877d59-8c1b-48b1-b92c-d199c3ff5f60.png">

**Comment by fajr365** [comment] 2023-03-06 11:26
Thanks for responding

baseResourceName - MLHCommunicator
userClientId - REMOVED
userClientSecret
authorClientId - REMOVED
authorClientSecret
graphAppId – REMOVED
graphAppSecret
senderUPNList- REMOVED
proactivelyInstallUserApp - true
userAppExternalId - 148a66bb-e83d-425a-927d-09f4299a9274
defaultCulture - en-US
supportedCultures - ar-SA,de-DE,en-US,es-ES,fr-FR,he-IL,ja-JP,ko-KR,pt-BR,ru-RU,zh-CN,zh-TW
customDomainOption - Azure Front Door
appDisplayName - MLH Company Communicator
appDescription - Broadcast messages to multiple teams and people in one go
appIconUrl - https://raw.githubusercontent.com/OfficeDev/microsoft-teams-apps-company-communicator/main/Manifest/color.png
headerText - MLH Company Communicator
headerLogoUrl - https://raw.githubusercontent.com/OfficeDev/microsoft-teams-apps-company-communicator/main/Source/CompanyCommunicator/ClientApp/src/assets/Images/mslogo.png
tenantId - REMOVED
hostingPlanSku - Standard
hostingPlanSize - 2
location - eastus
gitRepoUrl - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator.git
gitBranch - main
serviceBusWebAppRoleNameGuid - 958380b3-630d-4823-b933-f59d92cdcada
serviceBusPrepFuncRoleNameGuid - ce6ca916-08e9-4639-bfbe-9d098baf42ca
serviceBusSendFuncRoleNameGuid - 960365a2-c7bf-4ff3-8887-efa86fe4a163
serviceBusDataFuncRoleNameGuid - d42703bc-421d-4d98-bc4d-cd2bb16e5b0a
storageAccountWebAppRoleNameGuid - edd0cc48-2cf7-490e-99e8-131311e42030
storageAccountPrepFuncRoleNameGuid - 9332a9e9-93f4-48d9-8121-d279f30a732e
storageAccountDataFuncRoleNameGuid - 5b67af51-4a98-47e1-9d22-745069f51a13

From: Sai Venkat ***@***.***>
Sent: Monday, March 6, 2023 1:29 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Adorney, Frank ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Export status of sent messages (Issue #979)


This message originated from outside MLHS systems. Any attachments or links should be carefully considered before proceeding. Messages from our business partners still need to be reviewed and should not be opened if suspicious.
Please use the report phishing button to report a questionable email.

________________________________

--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
[image][user-images.githubusercontent.com]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png__;!!K_I4mMC9zg!ptVQulg4lrC0nZMR9NbbaG_3z7umtMr8jd01ARV1wmxtQS858ZXd3gsWf_Zg48GDZNrgOa-9JXCMsc5CsN8rWZU$>

--Click on Microsoft template

[image][user-images.githubusercontent.com]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png__;!!K_I4mMC9zg!ptVQulg4lrC0nZMR9NbbaG_3z7umtMr8jd01ARV1wmxtQS858ZXd3gsWf_Zg48GDZNrgOa-9JXCMsc5CycFQJD8$>

-- Then select inputs from left section where you can find the that are used. Please share them.
[image][user-images.githubusercontent.com]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/98143492/223035121-19877d59-8c1b-48b1-b92c-d199c3ff5f60.png__;!!K_I4mMC9zg!ptVQulg4lrC0nZMR9NbbaG_3z7umtMr8jd01ARV1wmxtQS858ZXd3gsWf_Zg48GDZNrgOa-9JXCMsc5C1L_dohs$>

**Comment by maye-vargas** [comment] 2023-03-06 12:10
Hello @gsv022 ; Checking I have the location "Eastus 2" within the implementation that was made.
But even so, it presents the error, before it worked but now it doesn't let it, and only with the other users that were given access to the authors, the one that did the execution in Azure, if it leaves it, but the others don't... No I know what it could be?

**Comment by cristianoag** [comment] 2023-03-07 11:52
This is not related to permissions. There is a bug on the bot service that is generating this error for everybody. Engineering is looking into the issue but there is no ETA.

**Comment by maye-vargas** [comment] 2023-03-07 12:08
Hello @cristianoag that is, the error may be the Authors Bot, but so far there is no reason for the error? or what could be the error?

**Comment by cristianoag** [comment] 2023-03-07 12:15
Engineering is looking into it. No eta at this moment.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-royavinash** [comment] 2023-03-07 23:58
@cristianoag Do you have any reference of the bug logged with the Bot team?

**Comment by iansoftel0** [comment] 2023-03-10 13:01
Any ideas on how to fix this or workaround this issue?

**Comment by maye-vargas** [comment] 2023-03-10 13:16
@cristianoag Any ideas on how to fix this or workaround this issue?

**Comment by cristianoag** [comment] 2023-03-10 16:11
The only workaround was already documented on the issue. Export directly from the tables.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cristianoag** [comment] 2023-03-10 18:14
I meant documented here https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/967

**Comment by gragosto** [comment] 2023-03-10 18:15
> Good morning, could you help me, when I export the status of the messages, I get an error, when I give permission, it tells me that "The card is blocked or does not have permissions", and it does not allow me to authorize to save in my Onedrive, what could it be? Could you please help me? ![image](https://user-images.githubusercontent.com/86726190/222534880-26acae8c-97eb-48ad-bff1-62d7d254e5a5.png)

I have also be impacted by this. 
When it will be solved?

**Comment by cristianoag** [comment] 2023-03-22 14:42
My custom version is now working ok on Americas region. Can someone test with the original CC version ?

**Comment by SynHam** [comment] 2023-03-22 15:36
> My custom version is now working ok on Americas region. Can someone test with the original CC version ?

Still not working for me on the original version.

**Comment by maye-vargas** [comment] 2023-03-23 19:03
@cristianoag I have not validated with the user, if it already works again with your version, I would think that it would already be there, I have your version, I would have to review

**Comment by Ukiman1014** [comment] 2023-03-29 20:48
This feature is still broken in the original version.  (All app permissions are green.)

**Comment by gsv022** [comment] 2023-04-19 13:52
@maye-vargas ,
Here is the workaround for the Export issue.

- Go to Azure Portal

- Click on the resource group that has been used for CC

- Go to Storage Account.

- Select Storage browser

- Go to Blob Containers

- Click on export data blobs.

- Copy the desired zip folder name from teams and search for required zip folder in export data blobs.

- Click on the zip folder that needs to download

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Download the zip file.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Once the issue is resolved,  we will update you.

**Comment by danielmacedo90** [comment] 2023-04-26 16:41
Any update? We are facing the same problem.

**Comment by gsv022** [comment] 2023-07-11 06:17
Hi @maye-vargas ,
Thanks for the patience. The issue has been fixed by the concerned team. Please check and confirm the export functionality working status from your end.

Keep us posted

**Comment by maye-vargas** [comment] 2023-07-11 12:17
Hello @gsv022 , Thanks!!

**Closed** 2023-07-22 19:00 UTC
Labels: answered, Needs: author feedback, Status: no recent activity
