### ISSUE TITLE
Company Communicator V4.0 Deployment issue

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#656] opened 2022-03-01 18:05 UTC
Receiving the following error during V4.0 deployment in Prod
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"}]}

**Comment by v-royavinash** [comment] 2022-03-02 04:44
Hi @EYSue ,

Could you please share the logs or the screenshot of the custom deployment progress to confirm which resources got failed. 

If the resources failed is of type **_Microsoft.Web/sites/sourcecontrols_**, please refer the resolution steps mentioned in the [troubleshooting guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting) #1.

**Comment by EYSue** [comment] 2022-03-02 09:52
Hi

Letting you know I am getting assistance on this issue from Erin Carter via our Account Manager, Scott Johnson.

Regards

Sue

**Comment by gsv022** [comment] 2022-03-10 05:20
Hi @EYSue , 
Could you please confirm if the issue is resolved?

**Comment by gsv022** [comment] 2022-03-31 12:34
Hi @EYSue ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. 

Hence we are closing the issue.

You may also always open a new issue or respond here if something does come back up. 
Thank you!

**Closed** 2022-03-31 12:34 UTC
Labels: answered
