### ISSUE TITLE
Latest Teams client update is allowing everybody to reply to bot messages

### ISSUE THREAD

**Issue by cristianoag** [OfficeDev/microsoft-teams-apps-company-communicator#629] opened 2022-02-10 13:30 UTC
The latest Teams client update is allowing all users to reply to CC bot messages. The problem now happens in every single deployment we have.

**Comment by v-royavinash** [comment] 2022-02-10 15:10
@cristianoag We have noted down it as an enhancement and will be providing a fix for it in upcoming releases. However will not be able to commit for any ETA for the issue. You can track the update with the already [existing issue #530 ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F530%23issuecomment-1034922123&data=04%7C01%7Cv-royavinash%40microsoft.com%7Cb727a9111e0240a00a9608d9ec9931f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637800965039008589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n%2BRzMYc91QQy2B%2FsF4VeGHJ4TT5rYcSBSgSDLQ%2B2ang%3D&reserved=0)

**Comment by Mikhail2k15** [comment] 2022-02-17 17:53
Hi @cristianoag, It is a known issue in the Teams platform, not CC. This regress occurs from time to time in any notification-only bots.

**Comment by cristianoag** [comment] 2022-02-17 17:56
I know that is a bug on Teams. The issue is that now the bug on Teams is affecting every single deployment of CC worldwide. Before the latest updates on the Teams client, the problem was located in just a few deployments. Now it is widespread and is causing a lot of trouble for multiple companies using Company Communicator.

**Comment by v-royavinash** [comment] 2022-02-18 15:43
@cristianoag , We acknowledge the concern and the issue with the notification-only bots. As its known issue in the Teams platform, the best we can do is to keep you updated whenever the issue is fixed.

**Comment by gsv022** [comment] 2022-05-04 11:30
Hi @cristianoag ,
For now we are closing this issue request as we provided the necessary information.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.

**Closed by gsv022** 2022-05-04 11:30 UTC
Labels: duplicate
