### ISSUE TITLE
Deployment Failing

### ISSUE THREAD

**Issue by shreebharaath** [OfficeDev/microsoft-teams-apps-company-communicator#665] opened 2022-03-10 06:57 UTC
Hi Team ,

           When i try to deploy company communicator from PowerShell i get this error please help me out with the next steps

![image](https://user-images.githubusercontent.com/39901961/157606228-fe9eed66-c501-4ab1-8e30-a0ab9d41f720.png)

**Comment by gsv022** [comment] 2022-03-10 07:11
Hi @shreebharaath ,

The above-mentioned issue occurs sometimes during ARM template deployment. Depending on the resource failed, please follow the below steps,
•	App service
•	Data-function : Azure function 
•	Prep-function : Azure function
•	Function: Azure function

User can manually fix the issue by following the below steps:
•	Go to the Azure portal  Resource group which got created  App Service
•	Go to the "Deployment center" section of the app service that failed to deploy.
•	Click on "Sync" to restart the deployment.

![Picture1](https://user-images.githubusercontent.com/98143492/157607743-b5fd8666-5cd3-4d4c-b056-ab7e1be3a408.png)

 
•	Post successful deployment of app service the Status will change as “Success”.
•	If you don’t see the Git [URL](https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git) mapped to app service, then please add External Git repo URL and then click on Sync.
•	Repeat the same steps for the failed Azure functions as well.

Since deployment failed, users may not have received the authorBotId, userBotId  and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your App Service.
•	authorBotId : It can be found in the "AuthorAppId" field of your configuration.
•	userBotId : It can be found in the "UserAppId" field of your configuration.
•	appDomain : It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

From here you can continue with the [further  steps of deployment.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by shreebharaath** [comment] 2022-03-10 07:13
Hi @gsv022 

I have already checked it there is nothing deployed

![image](https://user-images.githubusercontent.com/39901961/157608468-9e96494c-7be3-4a50-aa99-7ae01beb1ff1.png)

**Comment by gsv022** [comment] 2022-03-10 14:21
Hi @shreebharaath ,
To redeploy the app service issue please follow the below steps:

1. Click on Source and select external git.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/98143492/157680674-714c774a-d5d9-415c-abc1-21884ee5d7dd.png)


2. Go to repository paste this  [https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git](url)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/98143492/157680778-321a0ceb-3f07-473e-857d-9751c572405b.png)

3. Branch should be master.
4. Click Save and then click on sync. 

Another way is to repeat all the deployment procedure.

**Comment by v-royavinash** [comment] 2022-03-14 04:44
Hi @shreebharaath , Please let us know if the issue is resolved and we are good to close this request.

**Comment by shreebharaath** [comment] 2022-03-14 06:00
Hi @v-royavinash ,

                    I deleted all the resource group and redeployed from the beginning it worked . But i am not sure how to solve the error if reoccurs again

**Comment by gsv022** [comment] 2022-03-14 06:03
Hi @shreebharaath,
The steps mentioned above will fix the issue. If you encounter the issue later please reach out to us. 
For now closing the issue.

**Comment by shreebharaath** [comment] 2022-03-14 06:05
Hi @gsv022 ,
 
                Okay hope i don't face anymore issues thanks for the support @gsv022

**Closed** 2022-03-31 12:14 UTC
